language: node_js
node_js:
  - "8.11.2"
  - "10.3.0"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - "npm run test"
after_script: "npm install coveralls@3.0.1 && npm run test-ci && cat ./coverage/lcov.info | coveralls"